export { default as logo } from './logo.png'
export { default as morpho } from './morpho.png'
export { default as curt } from './curt.jpg'
export { default as forDoris } from './gleem.jpg'
export { default as doris } from './ForDoris.mp3'
export { default as seasons } from './seasons.jpg'
export { default as yesterdaytonight } from './yesterdaystonight.jpg'
